django_eveonline_doctrine_manager/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import permission_required
from django_eveonline_doctrine_manager.views import api, doctrines, fittings, skillplans, seeding
from .api import FittingView

urlpatterns = []

urlpatterns += [
    path('api/v2/fittings', FittingView.as_view(), name='v2-get-fittings'),
]

urlpatterns += [
    path('api/report/generate', api.generate_character_report,
         name="django-eveonline-doctrine-manager-api-generate-character-report"),
    path('api/report/doctrines', api.get_character_report,
         name='django-eveonline-doctrine-manager-api-report-doctrines'),
    path('api/doctrines', api.get_character_doctrines,
         name='django-eveonline-doctrine-manager-api-get-doctrines'),
    path('api/fittings', api.get_character_fittings,
         name='django-eveonline-doctrine-manager-api-get-fittings'),
    path('api/skillcheck', api.skillcheck_utility,
         name='django-eveonline-doctrine-manager-api-skillcheck'),
    path('api/hangarcheck', api.hangarcheck_utility,
         name='django-eveonline-doctrine-manager-api-hangarcheck'),
    path('api/fitting', api.get_fitting,
         name='django-eveonline-doctrine-manager-api-get-fitting'),
]

# Doctrines
urlpatterns += [
    path('doctrines/create/',
         permission_required(
             'django_eveonline_doctrine_manager.add_evedoctrine', raise_exception=True)
         (doctrines.DoctrineCreateView.as_view()),
         name="django-eveonline-doctrine-manager-doctrines-create"),

    path('doctrines/',
         permission_required(
             'django_eveonline_doctrine_manager.view_evedoctrine', raise_exception=True)
         (doctrines.DoctrineListView.as_view()),
         name="django-eveonline-doctrine-manager-doctrines-list"),

    path('doctrines/view/<int:id>/',
         permission_required(
             'django_eveonline_doctrine_manager.view_evedoctrine', raise_exception=True)
         (doctrines.DoctrineDetailView.as_view()),
         name="django-eveonline-doctrine-manager-doctrines-detail"),

    path('doctrines/view/<int:id>/audit/',
         permission_required(
             'django_eveonline_doctrine_manager.view_evecharacterdoctrinereport', raise_exception=True)
         (doctrines.DoctrineAuditView.as_view()),
         name="django-eveonline-doctrine-manager-doctrines-audit"),

    path('doctrines/update/<int:id>/',
         permission_required(
             'django_eveonline_doctrine_manager.change_evedoctrine', raise_exception=True)
         (doctrines.DoctrineUpdateView.as_view()),
         name="django-eveonline-doctrine-manager-doctrines-update"),

    path('doctrines/delete/<int:id>/',
         permission_required(
             'django_eveonline_doctrine_manager.delete_evedoctrine', raise_exception=True)
         (doctrines.DoctrineDeleteView.as_view()),
         name="django-eveonline-doctrine-manager-doctrines-delete"),
]

# Fittings
urlpatterns += [
    path('fittings/create',
         permission_required(
             'django_eveonline_doctrine_manager.add_evefitting', raise_exception=True)
         (fittings.FittingCreateView.as_view()),
         name="django-eveonline-doctrine-manager-fittings-create"),

    path('fittings',
         permission_required(
             'django_eveonline_doctrine_manager.view_evefitting', raise_exception=True)
         (fittings.FittingListView.as_view()),
         name="django-eveonline-doctrine-manager-fittings-list"),

    path('fittings/view/<int:id>',
         permission_required(
             'django_eveonline_doctrine_manager.view_evefitting', raise_exception=True)
         (fittings.FittingDetailView.as_view()),
         name="django-eveonline-doctrine-manager-fittings-detail"),

    path('fittings/view/<int:id>/audit/',
         permission_required(
             'django_eveonline_doctrine_manager.view_evecharacterdoctrinereport', raise_exception=True)
         (fittings.FittingAuditView.as_view()),
         name="django-eveonline-doctrine-manager-fittings-audit"),

    path('fittings/update/<int:id>',
         permission_required(
             'django_eveonline_doctrine_manager.change_evefitting', raise_exception=True)
         (fittings.FittingUpdateView.as_view()),
         name="django-eveonline-doctrine-manager-fittings-update"),

    path('fittings/delete/<int:id>',
         permission_required(
             'django_eveonline_doctrine_manager.delete_evefitting', raise_exception=True)
         (fittings.FittingDeleteView.as_view()),
         name="django-eveonline-doctrine-manager-fittings-delete"),

    path('fittings/market/',
         permission_required(
             'django_eveonline_doctrine_manager.view_evefittingmarketrule', raise_exception=True)
         (seeding.FittingMarketRuleListView.as_view()),
         name="django-eveonline-doctrine-manager-fittings-market"),

    path('fittings/market/stock/',
         permission_required(
             'django_eveonline_doctrine_manager.view_evefittingmarketrule', raise_exception=True)
         (seeding.update_stock),
         name="django-eveonline-doctrine-manager-fittings-stock"),
]

# Skillplans
urlpatterns += [
    path('skillplans/create',
         permission_required(
             'django_eveonline_doctrine_manager.add_eveskillplan', raise_exception=True)
         (skillplans.SkillPlanCreateView.as_view()),
         name="django-eveonline-doctrine-manager-skillplans-create"),

    path('skillplans',
         permission_required(
             'django_eveonline_doctrine_manager.view_eveskillplan', raise_exception=True)
         (skillplans.SkillPlanListView.as_view()),
         name="django-eveonline-doctrine-manager-skillplans-list"),

    path('skillplans/view/<int:id>',
         permission_required(
             'django_eveonline_doctrine_manager.view_eveskillplan', raise_exception=True)
         (skillplans.SkillPlanDetailView.as_view()),
         name="django-eveonline-doctrine-manager-skillplans-detail"),

    path('skillplans/update/<int:id>',
         permission_required(
             'django_eveonline_doctrine_manager.change_eveskillplan', raise_exception=True)
         (skillplans.SkillPlanUpdateView.as_view()),
         name="django-eveonline-doctrine-manager-skillplans-update"),

    path('skillplans/delete/<int:id>',
         permission_required(
             'django_eveonline_doctrine_manager.change_eveskillplan', raise_exception=True)
         (skillplans.SkillPlanDeleteView.as_view()),
         name="django-eveonline-doctrine-manager-skillplans-delete"),
]

# SRP
urlpatterns += [

]

django_eveonline_doctrine_manager/models.py
from django.db import models
from django.apps import apps
from django_eveonline_connector.models import EveStructure, EveEntity, EveCharacter, EveContract
from django_eveonline_connector.utilities.static.universe import resolve_type_name_to_type_id
from django_eveonline_doctrine_manager.utilities.abstractions import EveSkillList
from django.core.validators import MaxValueValidator, MinValueValidator
from django_singleton_admin.models import DjangoSingleton
from .utilities.fittings import parse_eft_format, get_required_skills, get_market_format, get_ship_name
import json, logging, re, roman

logger = logging.getLogger(__name__)

"""
Helper functions
"""

bootstrap_color_choices = (
    ('primary', 'Blue'),
    ('secondary', 'Gray'),
    ('success', 'Green'),
    ('danger', 'Red'),
    ('warning', 'Yellow'),
    ('info', 'Light Blue'),
    ('dark', 'Dark Gray'),
)


def get_skill_names_from_static_dump():
    import django_eveonline_doctrine_manager
    import os
    pth = os.path.dirname(django_eveonline_doctrine_manager.__file__)
    with open(pth + '/export/skills.json', 'r') as fp:
        skills = json.load(fp)

    return [ (skill, skill) for skill in skills.keys()]

class EveDoctrineSettings(DjangoSingleton):
    staging_structure = models.OneToOneField(EveStructure, on_delete=models.SET_NULL, null=True, blank=True)
    contract_entity = models.OneToOneField(EveEntity, on_delete=models.SET_NULL, null=True, blank=True)
    seeding_contract_prefix = models.CharField(max_length=12, blank=True, null=True, default=None)
    seeding_enabled = models.BooleanField(default=False)

    @staticmethod
    def get_instance():
        return EveDoctrineSettings.objects.all()[0]

    class Meta:
        verbose_name = "Doctrine Settings"
        verbose_name_plural = "Doctrine Settings"

"""
Core models
These are the main data models for the doctrine manager
"""
class EveDoctrine(models.Model):
    name = models.CharField(max_length=32)
    description = models.TextField(blank=True, null=True)
    tags = models.ManyToManyField("EveDoctrineManagerTag", blank=True)
    category = models.ForeignKey(
        "EveDoctrineCategory", on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def fittings(self):
        return EveFitting.objects.filter(doctrines__in=[self])
    
    @property
    def skill_plans(self):
        return EveSkillPlan.objects.filter(doctrines__in=[self])

    @property
    def character_list(self):
        return EveCharacter.objects.filter(corporation__track_characters=True)

    def __str__(self):
        return self.name
    
class EveFitting(models.Model):
    name = models.CharField(max_length=32)
    fitting = models.TextField()  # eft format
    description = models.TextField(blank=True, null=True)
    tags = models.ManyToManyField("EveDoctrineManagerTag", blank=True)
    doctrines = models.ManyToManyField("EveDoctrine", blank=True)
    roles = models.ManyToManyField("EveDoctrineRole", blank=True)
    # eve static info
    ship_id = models.IntegerField(editable=False, blank=True, null=True)
    ship_name = models.CharField(max_length=128, default="Unknown Hull")
    # associations 
    refit_of = models.ForeignKey("EveFitting", blank=True, null=True, default=None, on_delete=models.CASCADE)
    # globs
    required_skills_raw = models.TextField()
    parsed_format_raw = models.TextField(null=True, blank=True)
    market_format_raw = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.ship_id = resolve_type_name_to_type_id(get_ship_name(self))
        self.ship_name = get_ship_name(self)
        self.parsed_format_raw = json.dumps(parse_eft_format(self))
        super(EveFitting, self).save(*args, **kwargs)

    @property
    def market_format(self):
        return self.market_format_raw

    @property
    def parsed_format(self):
        return dict(json.loads(self.parsed_format_raw))

    @property
    def required_skills(self):
        return dict(json.loads(self.required_skills_raw))

    @property
    def refits(self):
        return EveFitting.objects.filter(refit_of=self)
    
    @property
    def character_list(self):
        return EveCharacter.objects.filter(corporation__track_characters=True)

    def get_missing_skills(self, character_id):
        character = EveCharacter.objects.get(external_id=character_id)
        return EveSkillList.get_missing_skills_from_json(self.required_skills, character_id)

class EveSkillPlan(models.Model):
    name = models.CharField(max_length=32)
    description = models.TextField(blank=True, null=True)
    skills = models.TextField()
    tags = models.ManyToManyField("EveDoctrineManagerTag", blank=True)
    doctrines = models.ManyToManyField("EveDoctrine", blank=True)
    roles = models.ManyToManyField("EveDoctrineRole", blank=True)

    def save(self, *args, **kwargs):
        super(EveSkillPlan, self).save(*args, **kwargs)

    def get_required_skills(self):
        cleaned_skill_list = []
        # clean skills from "SKILL V" format to "SKILL 1"
        skills = self.skills
        skills = skills.replace("<p>", "").replace("</p>", "")
        skills = skills.replace("<br>", "\n")
        for skill in filter(None, skills.split("\n")):
            skill_name = " ".join(skill.split(" ")[:-1])
            skill_level = roman.fromRoman("".join(skill.split(" ")[-1:]).rstrip("\n\r"))
            cleaned_skill_list.append(f"{skill_name} {skill_level}")
        return EveSkillList.from_list(cleaned_skill_list)

    def __str__(self):
        return self.name    

class EveFittingMarketRule(models.Model):
    fitting = models.OneToOneField(EveFitting, on_delete=models.CASCADE)
    requested_stock = models.IntegerField()
    structure = models.ForeignKey(EveStructure, on_delete=models.CASCADE)

    def __str__(self):
        return f"<{self.requested_stock} {self.fitting.name} @ {self.structure.name}>"

    @property 
    def required_name(self):
        prefix = EveDoctrineSettings.get_instance().seeding_contract_prefix
        if prefix:
            title = prefix + self.fitting.name
        else:
            title = self.fitting.name
        return title 

    @property
    def current_stock(self):
        title=self.required_name
        return EveContract.objects.filter(end_location_id=self.structure.structure_id, title=title, status="outstanding").count()

"""
Grouping models
Used to group fittings and doctrines for users and clarity.
"""
class EveRequiredSkill(models.Model):
    name = models.CharField(
        max_length=64, choices=get_skill_names_from_static_dump())
    level = models.IntegerField(
        validators=[MaxValueValidator(5), MinValueValidator(1)])
    skill_for = models.ForeignKey("EveSkillPlan", on_delete=models.CASCADE)

class EveDoctrineRole(models.Model):
    name = models.CharField(max_length=128)
    icon = models.URLField()
    color = models.CharField(max_length=32, choices=bootstrap_color_choices)


    def __str__(self):
        return self.name

class EveDoctrineCategory(models.Model):
    name = models.CharField(max_length=128)
    icon = models.URLField()
    color = models.CharField(max_length=32, choices=bootstrap_color_choices)

    def __str__(self):
        return self.name

class EveDoctrineManagerTag(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


"""
Reports
"""
class EveCharacterDoctrineReport(models.Model):
    """
    JSON report in the following format:
        {
            doctrines: [ Object doctrine (see below)],
            fittings: [ Object fitting (see below)],
            skillplans: [ Object skillplan (see below)],
        }

    Object formats
        doctrine: {
            "name": string, 
            skill_ready_fittings: [],
            hangar_ready_fittings: [],
        }

        fitting: {
            name: string, 
            type_name: string
            type_id: int
            missing_skills: {},
            in_hangar: bool
        }

        skillplan: {
            name: string,
            missing_skills: {},
        }
    """
    character = models.OneToOneField(EveCharacter, on_delete=models.CASCADE)
    data = models.TextField()

    # def save(self, *args, **kwargs):
    #     self.data = json.dumps(self.data)
    #     super(EveCharacterDoctrineReport, self).save(*args, **kwargs)

    def reset(self):
        self.data = json.dumps({
            "doctrines": {},
            "fittings": {},
            "skillplans": {}
        })
        self.save()
        return self

    def save_report(self, report):
        self.data = json.dumps(report, sort_keys=True, indent=4)
        self.save()

    def get_report(self):
        return dict(json.loads(self.data))

django_eveonline_doctrine_manager/views/seeding.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django_eveonline_doctrine_manager.models import EveFittingMarketRule
from django_eveonline_connector.tasks import update_character_contracts
from django.contrib import messages
from celery import group

class FittingMarketRuleListView(ListView):
    template_name = 'django_eveonline_doctrine_manager/adminlte/fittings/fitting_market_rules.html'
    model = EveFittingMarketRule

def update_stock(request):
    tokens = request.user.eve_tokens.all()
    characters = [token.evecharacter for token in tokens]
    job_group = group([update_character_contracts.s(character.external_id) for character in characters])
    dispatched_group = job_group.apply_async()
    messages.warning(request, "Contract update queued in the backend, refresh in a minute or so.")
    return redirect('django-eveonline-doctrine-manager-fittings-market')

django_eveonline_doctrine_manager/templates/django_eveonline_doctrine_manager/adminlte/skillplans/skillplan_delete.html
{% extends "base.html" %}

{% block title %}
Delete Skillplan
{% endblock %}


{% block breadcrumbs %}
<li class="breadcrumb-item"><a href="{% url 'django-eveonline-doctrine-manager-skillplans-list' %}">Skillplans</a></li>
<li class="breadcrumb-item"><a href="{% url 'django-eveonline-doctrine-manager-skillplans-detail' object.pk %}">View Skillplan</a></li>
{% endblock %}

{% block breadcrumb %}
Delete Skillplan
{% endblock %}


{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div class="card card-outline card-danger">
        <div class="card-header">
            <h3>Are you sure?</h3>
        </div>
        <div class="card-body">
            <p>You are about to delete this skillplan, this cannot be undone.</p>
        </div>
        <div class="card-footer">
            <a class="btn btn-default" href="{% url 'django-eveonline-doctrine-manager-skillplans-detail' object.pk %}">Cancel</a>
            <button class="btn btn-danger" type="submit">Confirm</button>
        </div>
    </div>
</form>
{% endblock %}

django_eveonline_doctrine_manager/templates/django_eveonline_doctrine_manager/adminlte/skillplans/skillplan_detail.html
{% extends "base.html" %}

{% block title %}
View Skillplan
{% endblock %}

{% block breadcrumbs %}
<li class="breadcrumb-item"><a href="{% url 'django-eveonline-doctrine-manager-skillplans-list' %}">Skillplans</a></li>
{% endblock %}

{% block breadcrumb %}
View Skillplan
{% endblock %}


{% block content %}
<div class="row">
    <div class="col-md-6">
        <div class="card card-primary card-outline">
            <div class="card-header">
                <h3 class="card-title">EFT Format</h3>
            </div>
            <div class="card-body">
                <textarea style="width:100%" onclick="this.select()" class="col-md-12" rows="15" readonly="readonly">{{object.skills}}</textarea>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card card-info card-outline">
            <div class="card-header">
                <h3 class="card-title">Description</h3>
            </div>
            <div class="card-body">
            <p>
                {% autoescape off %}
                {{object.description}}
                {% endautoescape %}
            </p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}
<script>
    $.fn.DataTable.ext.pager.numbers_length = 5;
    $(function () {
        $('table').DataTable({
            'paging': true,
            'lengthChange': true,
            'searching': true,
            'ordering': true,
            'order': [[1, 'asc']],
            'pageLength': 5,
            "autoWidth": false,
        })
    })
</script>

{% endblock %}

django_eveonline_doctrine_manager/templates/django_eveonline_doctrine_manager/adminlte/skillplans/skillplan_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Skillplans
{% endblock %}

{% block breadcrumbs %}
<li class="breadcrumb-item"><a href="{% url 'django-eveonline-doctrine-manager-skillplans-list' %}">Skillplans</a></li>
{% endblock %}

{% block breadcrumb %}
Skillplan Form
{% endblock %}


{% block head %}
<link rel="stylesheet" href="{% static 'adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">
{% endblock %}

{% block content %}
<div class="card card-outline card-warning">
    <div class="card-header ">
        <h3 class="card-title">
            Skillplan Form
        </h3>
    </div>
    <div class="card-body pad">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-success btn-block" type="submit" value="Submit">
        </form>
    </div>
</div>

{% endblock %}

{% block scripts %}
<script src="{% static 'adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js' %}"></script>
<script>
    $(function () {
        // Summernote
        $('#id_description').summernote()

    })
</script>
{% endblock %}

django_eveonline_doctrine_manager/templates/django_eveonline_doctrine_manager/adminlte/skillplans/skillplan_list.html
{% extends "base.html" %}

{% block title %}
Skillplans
{% endblock %}


{% block breadcrumb %}
Skillplans
{% endblock %}


{% block content %}
<div class="card card-primary card-outline">
    <div class="card-header">
        <h3 class="card-title">
            Skillplan Table
        </h3>
        {% if perms.django_eveonline_doctrine_manager.add_eveskillplan %}
        <a class="btn float-right" href="{% url 'django-eveonline-doctrine-manager-skillplans-create' %}">
            <i class="fa fa-plus"></i>
        </a>
        {% endif %}
    </div>
    <div class="card-body">
        <table class="table table-bordered table-striped dataTable">
            <thead>
                <th>Name</th>
                <th>Roles</th>
                <th>Actions</th>
                
            </thead>
            <tbody>
                {% for skillplan in object_list %}
                <tr>
                    <td>
                        <p class="pull-left">{{skillplan.name}}</p>
                        {% for tag in skillplan.tags.all %}
                        <span class="badge badge-primary float-right">{{tag}}</span>
                        {% endfor %}
                    </td>
                    <td class="hidden-xs">
                        {% for role in skillplan.roles.all %}
                        <span class="badge badge-{{role.color}}">{{role}}</span>
                        {% endfor %}
                    </td>
                    <td >
                        <div style="display: flex;" class="btn-group btn-group-md">
                            <a href="{% url 'django-eveonline-doctrine-manager-skillplans-detail' skillplan.pk %}" style="flex: 1;" class="btn btn-info fa fa-eye"></a>
                            {% if perms.django_eveonline_doctrine_manager.change_eveskillplan %}
                            <a href="{% url 'django-eveonline-doctrine-manager-skillplans-update' skillplan.pk %}" style="flex: 1;" class="btn btn-warning text-white fa fa-edit"></a>
                            {% endif %}
                            {% if perms.django_eveonline_doctrine_manager.delete_eveskillplan %}
                            <a href="{% url 'django-eveonline-doctrine-manager-skillplans-delete' skillplan.pk %}" style="flex: 1;" class="btn btn-danger fa fa-times-circle"></a>
                            {% endif %}
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="card-footer">
        
    </div>  
</div>

{% endblock %}

{% block scripts %}
<script>
    $.fn.DataTable.ext.pager.numbers_length = 5;
    $(function () {
        $('table').DataTable({
            'paging': true,
            'lengthChange': true,
            'searching': true,
            'ordering': true,
            'order': [[1, 'asc']],
            'pageLength': 10,
            "autoWidth": false,
        })
    })
</script>

{% endblock %}